### ISSUE TITLE
Running list of coros that hold the event loop for too long

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1980]
These coros have held the event loop for too long, and need to be more cooperative. The longest known blocking time is included:
- Last verified at a2c69cee88626c9
  - [x] `BasePeerPool._periodically_report_stats() running at /home/jcarver/code/trinity/p2p/peer_pool.py:553` 267.3s #1989 
  - [x] `BeamDownloader._store_nodes() done, defined at /home/jcarver/code/trinity/trinity/sync/beam/state.py:531` 6.0s #1984 
  - [x] `BeamBlockImporter._preview_address_load() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:811` 5.2s #1984 
  - [x] `BeamStateBackfill.run() running at /home/jcarver/code/trinity/trinity/sync/beam/backfill.py:142` 2.9s #1983 
  - [x] `_run() running at /home/jcarver/code/trinity/trinity/bootstrap.py:275` 0.3s
  - [ ] `coro=<GetNodeDataV65Exchange.__call__() running at /home/jcarver/code/trinity/trinity/protocol/eth/exchanges.py:105>  28.395 seconds`
  - [ ] `coro=<BeamDownloader._get_nodes() done, defined at /home/jcarver/code/trinity/trinity/sync/beam/state.py:571>  26.139 seconds`
  - [ ] `coro=<PingAndDisconnectIfIdle.run.<locals>.set_msg_received() done, defined at /home/jcarver/code/trinity/p2p/p2p_api.py:47>  26.128 seconds`
  - [ ] `<Handle _chain_future.<locals>._set_state created at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/futures.py:374>  24.48 seconds`
  - [ ] `coro=<BasePeer._handle_subscriber_message() done, defined at /home/jcarver/code/trinity/p2p/peer.py:324>  21.53 seconds`
  - [ ] `coro=<BeamDownloader._node_hashes_present() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:649>  19.858 seconds`
  - [ ] `coro=<Multiplexer._do_multiplexing() running at /home/jcarver/code/trinity/p2p/multiplexer.py:342>  18.585 seconds` #1991
  - [ ] `coro=<BeamDownloader._get_predictive_nodes_from_peer() done, defined at /home/jcarver/code/trinity/trinity/sync/beam/state.py:555>  18.081 seconds`
  - [ ] `coro=<BeamStateBackfill.pop_fastest_peasant() running at /home/jcarver/code/trinity/trinity/sync/beam/backfill.py:129>  16.53 seconds`
  - [ ] `coro=<BeamDownloader._get_nodes() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:576>  11.99 seconds`
  - [ ] `coro=<BaseManager._run_and_manage_task() running at /home/jcarver/code/async-service/async_service/base.py:300>  9.94 seconds`
  - [ ] `coro=<BeamDownloader.download_accounts() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:319>  4.408 seconds`
  - [ ] `coro=<PeerPoolEventServer.handle_stream() running at /home/jcarver/code/trinity/trinity/protocol/common/peer_pool_event_bus.py:196>` 2.1s
  - [ ] `coro=<AsyncioIsolatedComponent._loop_monitoring_task() running at /home/jcarver/code/trinity/trinity/extensibility/asyncio.py:28>  1.783 seconds`
  - [ ] `coro=<MissingDataEventHandler._serve_storage() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:1093>  1.07 seconds` #1990 
  - [ ] `coro=<BeamBlockImporter._request_address_nodes() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:889>  1.036 seconds`
  - [ ] `coro=<RegularChainBodySyncer._preview_ready_blocks() running at /home/jcarver/code/trinity/trinity/sync/full/chain.py:1088>  1.02 seconds`
  - [ ] `coro=<MissingDataEventHandler._serve_account() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:1050>  0.908 seconds` #1990

I collected this data with:
```diff
diff --git a/async_service/asyncio.py b/async_service/asyncio.py
index 3ae6abc..3a82653 100644
--- a/async_service/asyncio.py
+++ b/async_service/asyncio.py
@@ -32,10 +32,16 @@ class FunctionTask(BaseFunctionTask):
     #
     async def run(self) -> None:
         try:
-            await self._async_fn(*self._async_fn_args)
+            # Name the task, to make it easier to identify which task is holding the event loop too long
+            await asyncio.create_task(
+                self._async_fn(*self._async_fn_args),
+                name=self.name,
+            )
             if self.daemon:
                 raise DaemonTaskExit(f"Daemon task {self} exited")
```
(I think the `create_task` part is more important than the `name=` part)

---

These are all suspect, since any of them could be caused by the logger. Not actively pursuing...
  - [ ] `SkeletonSyncer.run() running at /home/jcarver/code/trinity/trinity/sync/common/headers.py:129` 800s (not a typo!)
  - [ ] `Multiplexer._do_multiplexing() running at /home/jcarver/code/trinity/p2p/multiplexer.py:333` 6.3s
  - [ ] `BeamDownloader._match_predictive_node_requests_to_peers() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:466` 4.4s
  - [ ] `BasePeer._handle_subscriber_message() done, defined at /home/jcarver/code/trinity/p2p/peer.py:324` 3.7s
  - [ ] `PeerPoolEventServer.handle_native_peer_messages() running at /home/jcarver/code/trinity/trinity/protocol/common/peer_pool_event_bus.py:254` 3.3s
  - [ ] `StreamReader.readexactly() running at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/streams.py:723` 2.4s -- interesting...
  - [ ] `BeamDownloader._get_predictive_nodes_from_peer() done, defined at /home/jcarver/code/trinity/trinity/sync/beam/state.py:535` 2.1s
  - [ ] `Connection._feed_protocol_handlers() running at /home/jcarver/code/trinity/p2p/connection.py:225` 2.0s
  - [ ] `BasePeerPool.connect_to_node() running at /home/jcarver/code/trinity/p2p/peer_pool.py:452` 1.9s
  - [ ] `RegularChainBodySyncer._import_ready_blocks() running at /home/jcarver/code/trinity/trinity/sync/full/chain.py:1145` 1.0s

**Comment by gsalgado** [comment]
> _run() running at /home/jcarver/code/trinity/trinity/bootstrap.py:275  0.3s

This one is only called upon startup and it's where `asyncio-rip` runs the subprocess for a component, so I don't think there's much we can do to avoid it blocking for a bit. And even if there was I don't think it would improve startup time significantly

**Comment by carver** [comment]
Agreed, just included it for completeness. But I'll check it off as `WONTFIX` for now.

**Comment by gsalgado** [comment]
> Connection._feed_protocol_handlers() running at /home/jcarver/code/trinity/p2p/connection.py:225

This one may be fixed in #1964 (https://github.com/ethereum/trinity/pull/1964/files#diff-0677b3758440107726c19b15c4d05f0cR280-R281)

**Comment by gsalgado** [comment]
> Multiplexer._do_multiplexing() running at /home/jcarver/code/trinity/p2p/multiplexer.py:333 6.3s

This one is interesting because `_handle_commands()` consumes items from an async iterator that relinquishes control back to the event loop on every iteration. But one of the things it does is decoding of messages, which I expect could take long but hopefully not 6s

**Comment by cburgdorf** [comment]
>But one of the things it does is decoding of messages

Which at least will get a nice performance boost with the new rust based RLP decoding that is in the works.

**Comment by carver** [comment]
Ahah, I got a lead on why we have some coroutines complaining here that don't make any sense!

Check this out:
```
   DEBUG  2020-08-17 14:06:10,881           ETHPeerPool  ETHPeer (eth, 63) <Session <Node(0xaa9c91@54.165.18.108)> 490c579f-49ba-462f-bf24-e7c6a47dc70d>: uptime=3m18s, received_msgs=1590
   DEBUG  2020-08-17 14:06:10,881           ETHPeerPool  client_version_string='teth/v0.1/linux/go1.12.14'
   DEBUG  2020-08-17 14:06:10,882           ETHPeerPool      <class 'trinity.protocol.eth.commands.BlockBodiesV65'>: None!
   DEBUG  2020-08-17 14:10:38,179           ETHPeerPool      <class 'trinity.protocol.eth.commands.BlockHeadersV65'>: msgs=1  items=2  rtt=19.10/1.91/0.00  ips=0.05243  timeouts=0  quality=5
   DEBUG  2020-08-17 14:10:38,179           ETHPeerPool      <class 'trinity.protocol.eth.commands.NodeDataV65'>: msgs=1  items=0  rtt=19.50/10.00/0.00  ips=0.00000  timeouts=1  quality=0
...
 WARNING  2020-08-17 14:10:38,182               asyncio  Executing <Task pending name='_periodically_report_stats' coro=<BasePeerPool._periodically_report_stats() running at /home/jcarver/code/trinity/p2p/peer_pool.py:553> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8ce0473550>()] created at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/tasks.py:643> cb=[<TaskWakeupMethWrapper object at 0x7f8cf404e6d0>()] created at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/tasks.py:382> took 267.314 seconds
```
Note that there is a 4.5 minute gap in the middle of reporting a single peer's stats.

The series of extra stats about a peer is logged here:
https://github.com/ethereum/trinity/blob/1af692e67f4c54fcd986e6fad6a9e51bbbfe667f/p2p/peer_pool.py#L547-L548

The extra stats are returned as a tuple, so there is no extra computation between each loop iteration. So it seems that the only remaining explanation is logging itself.

**Comment by carver** [comment]
With the logging issue pushed out of the way (I think), I'm still getting some surprises. Here are some asyncio warnings, and how long they held the loop:
```
coro=<GetNodeDataV65Exchange.__call__() running at /home/jcarver/code/trinity/trinity/protocol/eth/exchanges.py:105>  28.395 seconds
coro=<BeamDownloader._get_nodes() done, defined at /home/jcarver/code/trinity/trinity/sync/beam/state.py:571>  26.139 seconds
coro=<PingAndDisconnectIfIdle.run.<locals>.set_msg_received() done, defined at /home/jcarver/code/trinity/p2p/p2p_api.py:47>  26.128 seconds
<Handle _chain_future.<locals>._set_state created at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/futures.py:374>  24.48 seconds
coro=<BasePeer._handle_subscriber_message() done, defined at /home/jcarver/code/trinity/p2p/peer.py:324>  21.53 seconds
coro=<BeamDownloader._node_hashes_present() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:649>  19.858 seconds
coro=<Multiplexer._do_multiplexing() running at /home/jcarver/code/trinity/p2p/multiplexer.py:342>  18.585 seconds
coro=<BeamDownloader._get_predictive_nodes_from_peer() done, defined at /home/jcarver/code/trinity/trinity/sync/beam/state.py:555>  18.081 seconds
coro=<BeamStateBackfill.pop_fastest_peasant() running at /home/jcarver/code/trinity/trinity/sync/beam/backfill.py:129>  16.53 seconds
coro=<BeamDownloader._get_nodes() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:576>  11.99 seconds
coro=<BaseManager._run_and_manage_task() running at /home/jcarver/code/async-service/async_service/base.py:300>  9.94 seconds
coro=<BeamDownloader.download_accounts() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:319>  4.408 seconds
coro=<AsyncioIsolatedComponent._loop_monitoring_task() running at /home/jcarver/code/trinity/trinity/extensibility/asyncio.py:28>  1.783 seconds
coro=<MissingDataEventHandler._serve_storage() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:1093>  1.07 seconds
coro=<BeamBlockImporter._request_address_nodes() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:889>  1.036 seconds
coro=<RegularChainBodySyncer._preview_ready_blocks() running at /home/jcarver/code/trinity/trinity/sync/full/chain.py:1088>  1.02 seconds
coro=<MissingDataEventHandler._serve_account() running at /home/jcarver/code/trinity/trinity/sync/beam/chain.py:1050>  0.908 seconds
```

**Comment by carver** [comment]
This is the line that sometimes holds the event loop for too long during `_do_multiplexing`:
https://github.com/ethereum/trinity/blob/12103e8efe0bdb79b7febf5bb5a18b8d5ccec4d5/p2p/multiplexer.py#L90

Opening a PR soon

**Comment by carver** [comment]
Waaat:
```
 WARNING  2020-08-19 15:56:19,285               asyncio  Executing <Task pending name='BeamDownloader._wait_for_nodes->_node_hashes_present' coro=<BeamDownloader._node_hashes_present() running at /home/jcarver/code/trinity/trinity/sync/beam/state.py:622> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/futures.py:360, <TaskWakeupMethWrapper object at 0x7f6700259370>()] created at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/futures.py:388> cb=[<TaskWakeupMethWrapper object at 0x7f66f02e6670>()] created at /home/jcarver/.pyenv/versions/3.8.5/lib/python3.8/asyncio/tasks.py:382> took 0.735 seconds
```
https://github.com/ethereum/trinity/blob/12103e8efe0bdb79b7febf5bb5a18b8d5ccec4d5/trinity/sync/beam/state.py#L618-L627

How could this possibly be holding the event loop for 0.7s?
