### ISSUE TITLE
Split and merge #465 to master

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#488]
### What is wrong?

As #465 getting fat and the exploration is nearly maximized, it's time to split it to smaller PRs and merge them back to master.

### How can it be fixed

- [x] Update a state machine class and a chain class for the testnet. #489
- [x] Add Slot ticker #490
- [x] Add validator service #525
- [x] Add validator service and slot ticker to the beacon plugin. #594
- [x] Update sync and the receiving server. #580
- [x] Add integration tests for two `trinity-beacon` clients initiating and syncing #594
- [x] The network setup experience #516
