### ISSUE TITLE
Discv5 Wire Protocol Tracking Issue

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#668]
# Goal

A very basic plugin that receives UDP messages, passes them according to the sender address to a peer handler, and performs a handshake.

# Subtasks

- [x] [ENR](https://github.com/ethereum/trinity/pull/586) (with v4 identity scheme)
  - [x] [Non-recoverable signatures](https://github.com/ethereum/eth-keys/pull/58)
  - [x] [Compressed public keys](https://github.com/ethereum/eth-keys/pull/56)
- [x] [Session encryption/decryption](https://github.com/ethereum/trinity/pull/652)
- [ ] Handshake
- [x] [Message types](https://github.com/ethereum/trinity/pull/650)
- [x] Packets
  - [x] Encoding/Decoding
    - [x] [who are you](https://github.com/ethereum/trinity/pull/736)
    - [x] [auth header and auth tag](https://github.com/ethereum/trinity/pull/737)
    - [ ] ~~[Encoding/Decoding](#723)~~
  - [x] Content preparation helpers
    - [x] [who are you](https://github.com/ethereum/trinity/pull/738)
    - [x] [auth header](https://github.com/ethereum/trinity/pull/741)
    - [x] [auth tag](https://github.com/ethereum/trinity/pull/739)
  - [x] Packet decryption
    - [x] [Message decryption](https://github.com/ethereum/trinity/pull/743)
    - [x] [Auth header decryption](https://github.com/ethereum/trinity/pull/747)

# References

- [ENR EIP](http://eips.ethereum.org/EIPS/eip-778)
- [Wire protocol spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md)

**Comment by pipermerriam** [comment]
FYI: https://eips.ethereum.org/EIPS/eip-868
